openapi: 3.1.0

info:
  title: HealConnect Api
  description: "Api für Hals- und Kopf-Krebs Patienten Kommunikation"
  version: 1.0.0

servers:
  - url: http:localhost:8080/v1

tags:
  - login

paths:
  /patientlogin:
    post:
      tags:
        - login
      summary: Logge dich als Patient ein
      operationId: loginPatient
      responses:
        200:
          description: Erfolgreicher Login
        401:
          description: Sie sind nicht authorisiert
      requestBody:
        description: Die Login-Daten des Patienten
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatientLogin"

components:
  schemas:
    PatientLogin:
      description: Das Login-Objekt eines Patienten
      type: object
      properties:
        username:
          description: Der Benutzername oder die E-Mailadresse des Patienten
          type: string
        password:
          description: Das Passwort als hash
          type: string
      required:
        - username
        - password
